spring:
#  thymeleaf
  thymeleaf:
    cache: false
#  数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncodeing=UTF-8&useSSL=false&serverTimezone=GMT
    username: root
    password: root
    hikari:
#      连接池名称
      pool-name: testHikari
#      最小空闲连接数
      minimum-idle: 5
#      空闲连接最大超时时间
      idle-timeout: 300000
#      连接最大存活时间
      max-lifetime: 300000
#      从连接池返回的连接自动提交
      auto-commit: true
#      最大连接数
      maximum-pool-size: 10
#      连接超时时间
      connection-timeout: 30000

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5



mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.cx

logging:
  level:
    com.cx.seckill.mapper: debug

server:
  port: 8088
